version: '3.8'

services:
  notisbak:
    container_name: notisbak
    image: atareao:notisbak:latest
    init: true
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - proxy
      - internal
    logging:
      driver: journald
    labels:
      - traefik.enable=true
      - traefik.http.services.notisbak.loadbalancer.server.port=${PORT}
      - traefik.http.routers.notisbak.entrypoints=web
      - traefik.http.routers.notisbak.rule=Host(`${FQDN}`)
      - traefik.http.middlewares.notisbak-https-redirect.redirectscheme.scheme=websecure
      - traefik.http.routers.notisbak.middlewares=notisbak-https-redirect
      - traefik.http.routers.notisbak-secure.entrypoints=websecure
      - traefik.http.routers.notisbak-secure.rule=Host(`${FQDN}`)
      - traefik.http.routers.notisbak-secure.tls=true
      - traefik.http.routers.notisbak-secure.tls.certresolver=letsencrypt

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    logging:
      driver: journald
    networks:
      - proxy
      - internal

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: atareao@atareao.es
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    logging:
      driver: journald
    networks:
      - proxy
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.services.nbpgadmin.loadbalancer.server.port=80
      - traefik.http.routers.nbpgadmin.entrypoints=web
      - traefik.http.routers.nbpgadmin.rule=Host(`${FQDN}`)
      - traefik.http.middlewares.nbpgadmin-https-redirect.redirectscheme.scheme=websecure
      - traefik.http.routers.nbpgadmin.middlewares=nbpgadmin-https-redirect
      - traefik.http.routers.nbpgadmin-secure.entrypoints=websecure
      - traefik.http.routers.nbpgadmin-secure.rule=Host(`${FQDN}`)
      - traefik.http.routers.nbpgadmin-secure.tls=true
      - traefik.http.routers.nbpgadmin-secure.tls.certresolver=letsencrypt
