/**** Registro y validación ****/

POST http://{{NOTISBAK_FQDN}}/auth/register
Content-Type: application/json

{
    "email": "{{EMAIL}}",
    "password": "{{PASSWORD}}"
}

POST https://{{NOTISBAK_FQDN}}/auth/login
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "email": "{{EMAIL}}",
    "password": "{{PASSWORD}}"
}

GET http://{{NOTISBAK_FQDN}}/auth/
Accept: application/json
Authorization: Bearer {{TOKEN}}

GET https://{{NOTISBAK_FQDN}}/auth/validate
Authorization: Bearer {{TOKEN}}

/**** Swagger ****/

GET https://{{NOTISBAK_FQDN}}/api-doc/openapi.json

GET https://{{NOTISBAK_FQDN}}/swagger-ui/

/**** Test ****/

GET https://{{NOTISBAK_FQDN}}/api/v1/
Accept: application/json
Authorization: Bearer {{TOKEN}}

/**** Labels ****/

GET https://{{NOTISBAK_FQDN}}/api/v1/labels
Accept: application/json
Authorization: Bearer {{TOKEN}}

GET https://{{NOTISBAK_FQDN}}/api/v1/labels/1
Accept: application/json
Authorization: Bearer {{TOKEN}}

POST https://{{NOTISBAK_FQDN}}/api/v1/labels
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "name": "Etiqueta 6"
}

DELETE https://{{NOTISBAK_FQDN}}/api/v1/labels/1
Accept: application/json
Authorization: Bearer {{TOKEN}}


/**** CATEGORIES ****/

GET https://{{NOTISBAK_FQDN}}/api/v1/categories
Authorization: Bearer {{TOKEN}}

GET https://{{NOTISBAK_FQDN}}/api/v1/categories/11
Authorization: Bearer {{TOKEN}}

POST https://{{NOTISBAK_FQDN}}/api/v1/categories
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "name": "Categoria 4"
}

DELETE https://{{NOTISBAK_FQDN}}/api/v1/categories/13
Authorization: Bearer {{TOKEN}}

/**** NOTES ****/

GET https://{{NOTISBAK_FQDN}}/api/v1/notes
Authorization: Bearer {{TOKEN}}

POST https://{{NOTISBAK_FQDN}}/api/v1/notes
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "title": "Nota 3"
}

PUT https://{{NOTISBAK_FQDN}}/notes
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "id": 1,
    "title": "Nota 2",
    "body": "cosa rara"
}

DELETE https://{{NOTISBAK_FQDN}}/notes/5
GET https://{{NOTISBAK_FQDN}}/api/v1/notes
Accept: application/json
Authorization: Bearer {{TOKEN}}
