POST http://{{TEST_FQDN}}/auth/register
Content-Type: application/json

{
    "email": "{{EMAIL}}",
    "password": "{{PASSWORD}}"
}

POST http://{{TEST_FQDN}}/auth/login
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "email": "{{EMAIL}}",
    "password": "{{PASSWORD}}"
}

GET http://{{TEST_FQDN}}/auth/
Accept: application/json
Authorization: Bearer {{TOKEN}}

GET http://{{TEST_FQDN}}/auth/validate
Authorization: Bearer {{TOKEN}}

GET http://{{TEST_FQDN}}/api/v1/notes
Accept: application/json
Authorization: Bearer {{TOKEN}}

GET http://{{TEST_FQDN}}/api/v1/labels
Accept: application/json
Authorization: Bearer {{TOKEN}}


POST http://{{TEST_FQDN}}/users/register
Content-Type: application/json

{
    "email": "{{EMAIL}}",
    "password": "{{PASSWORD}}"
}


GET https://{{NOTISBAK_FQDN}}/

GET https://{{NOTISBAK_FQDN}}/api-doc/openapi.json

GET https://{{NOTISBAK_FQDN}}/swagger-ui/

GET https://{{NOTISBAK_FQDN}}/notes

POST https://{{NOTISBAK_FQDN}}/notes
Content-Type: application/json

{
    "title": "Nota 2"
}

PUT https://{{NOTISBAK_FQDN}}/notes
Content-Type: application/json

{
    "id": 1,
    "title": "Nota 2",
    "body": "cosa rara"
}

DELETE https://{{NOTISBAK_FQDN}}/notes/5

GET https://{{NOTISBAK_FQDN}}/categories

POST https://{{NOTISBAK_FQDN}}/categories
Content-Type: application/json

{
    "name": "Categoria 1"
}

GET https://{{NOTISBAK_FQDN}}/labels

POST https://{{NOTISBAK_FQDN}}/labels
Content-Type: application/json

{
    "name": "Etiqueta 1"
}

