POST http://localhost:{{PORT}}/auth/register
Content-Type: application/json

{
    "email": "{{EMAIL}}",
    "password": "{{PASSWORD}}"
}

POST http://localhost:{{PORT}}/auth/login
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "email": "{{EMAIL}}",
    "password": "{{PASSWORD}}"
}

GET http://localhost:8080/auth/
Accept: application/json
Authorization: Bearer {{TOKEN}}

GET http://localhost:8080/api/v1/notes
Accept: application/json
Authorization: Bearer {{TOKEN}}


GET http://localhost:8080/login
Accept: application/json

POST http://localhost:8080/users/register
Content-Type: application/json

{
    "email": "{{sample_email}}",
    "password": "{{sample_password}}"
}


GET http://{{NOTISBAK_FQDN}}/

GET http://{{NOTISBAK_FQDN}}/api-doc/openapi.json

GET http://{{NOTISBAK_FQDN}}/swagger-ui/

GET http://{{NOTISBAK_FQDN}}/notes

POST http://{{NOTISBAK_FQDN}}/notes
Content-Type: application/json

{
    "title": "Nota 2"
}

PUT http://{{NOTISBAK_FQDN}}/notes
Content-Type: application/json

{
    "id": 1,
    "title": "Nota 2",
    "body": "cosa rara"
}

DELETE http://{{NOTISBAK_FQDN}}/notes/5

GET http://{{NOTISBAK_FQDN}}/categories

POST http://{{NOTISBAK_FQDN}}/categories
Content-Type: application/json

{
    "name": "Categoria 1"
}

GET http://{{NOTISBAK_FQDN}}/labels

POST http://{{NOTISBAK_FQDN}}/labels
Content-Type: application/json

{
    "name": "Etiqueta 1"
}

