GET http://{{NOTISBAK_FQDN}}/

GET http://{{NOTISBAK_FQDN}}/notes

GET http://{{NOTISBAK_FQDN}}/swagger-ui/api-doc/openapi.json

POST http://{{NOTISBAK_FQDN}}/notes
Content-Type: application/json

{
    "title": "Nota 2"
}

PUT http://{{NOTISBAK_FQDN}}/notes
Content-Type: application/json

{
    "id": 1,
    "title": "Nota 2",
    "body": "cosa rara"
}

GET http://{{NOTISBAK_FQDN}}/categories

POST http://{{NOTISBAK_FQDN}}/categories
Content-Type: application/json

{
    "name": "Categoria 1"
}

GET http://{{NOTISBAK_FQDN}}/labels

POST http://{{NOTISBAK_FQDN}}/labels
Content-Type: application/json

{
    "name": "Etiqueta 1"
}

