GET http://localhost:8080/

GET http://localhost:8080/notes

GET http://localhost:8080/swagger-ui/api-doc/openapi.json

POST http://localhost:8080/notes
Content-Type: application/json

{
    "title": "Nota 2"
}

GET http://localhost:8080/categories

POST http://localhost:8080/categories
Content-Type: application/json

{
    "name": "Nota 1"
}

